apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-app
  labels:
    app: dr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dr-app
  template:
    metadata:
      labels:
        app: dr-app
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dr-app-svc
spec:
  selector:
    app: dr-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
