apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dr-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dr-app-svc
            port:
              number: 80
